// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxuwt1ff1Lf57-XjOQrKnS3HpWkR1OJis',
    appId: '1:953002727773:web:08d18ac65af390699c30b4',
    messagingSenderId: '953002727773',
    projectId: 'ecommerceapp-2dfcb',
    authDomain: 'ecommerceapp-2dfcb.firebaseapp.com',
    storageBucket: 'ecommerceapp-2dfcb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp6RZFFOEdj2AR0w0jvUyhMtpSpS3-qkE',
    appId: '1:953002727773:android:0f81e9ee6bed4cd09c30b4',
    messagingSenderId: '953002727773',
    projectId: 'ecommerceapp-2dfcb',
    storageBucket: 'ecommerceapp-2dfcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO5mvdsJe9FhNhNI5Ny9WGZ_iatSqv2AY',
    appId: '1:953002727773:ios:f8c81947aae00e1b9c30b4',
    messagingSenderId: '953002727773',
    projectId: 'ecommerceapp-2dfcb',
    storageBucket: 'ecommerceapp-2dfcb.appspot.com',
    androidClientId: '953002727773-am81m9ink6o12ogop6hll1gjrbgidruv.apps.googleusercontent.com',
    iosClientId: '953002727773-l5ktvqu76rsaus0r83j0el72nqml3vuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO5mvdsJe9FhNhNI5Ny9WGZ_iatSqv2AY',
    appId: '1:953002727773:ios:f8c81947aae00e1b9c30b4',
    messagingSenderId: '953002727773',
    projectId: 'ecommerceapp-2dfcb',
    storageBucket: 'ecommerceapp-2dfcb.appspot.com',
    androidClientId: '953002727773-am81m9ink6o12ogop6hll1gjrbgidruv.apps.googleusercontent.com',
    iosClientId: '953002727773-l5ktvqu76rsaus0r83j0el72nqml3vuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxuwt1ff1Lf57-XjOQrKnS3HpWkR1OJis',
    appId: '1:953002727773:web:34d159957cd8c9539c30b4',
    messagingSenderId: '953002727773',
    projectId: 'ecommerceapp-2dfcb',
    authDomain: 'ecommerceapp-2dfcb.firebaseapp.com',
    storageBucket: 'ecommerceapp-2dfcb.appspot.com',
  );

}